project:
  title: "analysis"
  render:
    - scripts/04_mutation/03_numbat.mutation.qmd

author: Kristy Ou

editor: visual

execute:
  echo: true
  eval: false
  include: true
  message: false
  warning: false
  
format: 
  html: 
    code-fold: true
    code-line-numbers: false
    theme: sandstone
    embed-resources: true
    
code-tools: true    
code-overflow: scroll
default-image-extension: svg
fig-cap-location: top
highlight-style: pygments
number-sections: false
toc: true
toc-location: left


